/*
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.aumReport.aum.entity;

import jakarta.persistence.*;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * JPA entity class for "Custodian"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="custodian", schema="public" )
public class Custodian implements Serializable {
    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    private int        id ;

    //--- OTHER DATA FIELDS
    @Column(name="created_timestamp")
    private LocalDateTime   createdTimestamp ;

    @Column(name="updated_timestamp")
    private LocalDateTime   updatedTimestamp ;

    @Column(name="created_by")
    private Integer         createdBy ;

    @Column(name="updated_by")
    private Integer         updatedBy ;

    @Column(name="name", length=2147483647)
    private String          name ;

    /**
     * Constructor
     */
    public Custodian() {
        super();
    }

    public void setId( int id ) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    public void setCreatedTimestamp( LocalDateTime createdTimestamp ) {
        this.createdTimestamp = createdTimestamp;
    }

    public LocalDateTime getCreatedTimestamp() {
        return this.createdTimestamp;
    }

    public void setUpdatedTimestamp( LocalDateTime updatedTimestamp ) {
        this.updatedTimestamp = updatedTimestamp;
    }

    public LocalDateTime getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy;
    }

    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Custodian[");
        sb.append("id=").append(id);
        sb.append(separator).append("createdTimestamp=").append(createdTimestamp);
        sb.append(separator).append("updatedTimestamp=").append(updatedTimestamp);
        sb.append(separator).append("createdBy=").append(createdBy);
        sb.append(separator).append("updatedBy=").append(updatedBy);
        sb.append(separator).append("name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}
