/*
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.aumReport.aum.entity;

import jakarta.persistence.*;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * JPA entity class for "Holding"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="holding", schema="public" )
public class Holding implements Serializable {
    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    private int        id ;

    //--- OTHER DATA FIELDS
    @Column(name="created_timestamp")
    private LocalDateTime   createdTimestamp ;

    @Column(name="updated_timestamp")
    private LocalDateTime   updatedTimestamp ;

    @Column(name="created_by")
    private Integer         createdBy ;

    @Column(name="updated_by")
    private Integer         updatedBy ;

    @Column(name="account_id")
    private int             accountId ;

    @Column(name="product_id")
    private Integer         productId ;

    @Column(name="asset_id")
    private int             assetId ;

    @Column(name="asset_product_mapping_id")
    private Integer         assetProductMappingId ;

    @Column(name="value")
    private double          value ;

    @Column(name="cost_basis")
    private double          costBasis ;

    @Column(name="short_term_realized_gain")
    private double          shortTermRealizedGain ;

    @Column(name="short_term_unrealized_gain")
    private double          shortTermUnrealizedGain ;

    @Column(name="long_term_realized_gain")
    private double          longTermRealizedGain ;

    @Column(name="long_term_unrealized_gain")
    private double          longTermUnrealizedGain ;


    /**
     * Constructor
     */
    public Holding() {
        super();
    }

    public void setId( int id ) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    public void setCreatedTimestamp( LocalDateTime createdTimestamp ) {
        this.createdTimestamp = createdTimestamp;
    }

    public LocalDateTime getCreatedTimestamp() {
        return this.createdTimestamp;
    }

    public void setUpdatedTimestamp( LocalDateTime updatedTimestamp ) {
        this.updatedTimestamp = updatedTimestamp;
    }

    public LocalDateTime getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy;
    }

    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setAccountId( int accountId ) {
        this.accountId = accountId;
    }

    public int getAccountId() {
        return this.accountId;
    }

    public void setProductId( Integer productId ) {
        this.productId = productId;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setAssetId( int assetId ) {
        this.assetId = assetId;
    }

    public int getAssetId() {
        return this.assetId;
    }

    public void setAssetProductMappingId( Integer assetProductMappingId ) {
        this.assetProductMappingId = assetProductMappingId;
    }

    public Integer getAssetProductMappingId() {
        return this.assetProductMappingId;
    }

    public void setValue( double value ) {
        this.value = value;
    }

    public double getValue() {
        return this.value;
    }

    public void setCostBasis( double costBasis ) {
        this.costBasis = costBasis;
    }

    public double getCostBasis() {
        return this.costBasis;
    }

    public void setShortTermRealizedGain( double shortTermRealizedGain ) {
        this.shortTermRealizedGain = shortTermRealizedGain;
    }

    public double getShortTermRealizedGain() {
        return this.shortTermRealizedGain;
    }

    public void setShortTermUnrealizedGain( double shortTermUnrealizedGain ) {
        this.shortTermUnrealizedGain = shortTermUnrealizedGain;
    }

    public double getShortTermUnrealizedGain() {
        return this.shortTermUnrealizedGain;
    }

    public void setLongTermRealizedGain( double longTermRealizedGain ) {
        this.longTermRealizedGain = longTermRealizedGain;
    }

    public double getLongTermRealizedGain() {
        return this.longTermRealizedGain;
    }

    public void setLongTermUnrealizedGain( double longTermUnrealizedGain ) {
        this.longTermUnrealizedGain = longTermUnrealizedGain;
    }

    public double getLongTermUnrealizedGain() {
        return this.longTermUnrealizedGain;
    }


    public Holding clone(boolean includeKeys) {
        Holding copy = new Holding();
        if (includeKeys) {
            copy.id = this.id;
        }
        copy.createdTimestamp = this.createdTimestamp;
        copy.updatedTimestamp = this.updatedTimestamp;
        copy.createdBy = this.createdBy;
        copy.updatedBy = this.updatedBy;
        copy.accountId = this.accountId;
        copy.productId = this.productId;
        copy.assetId = this.assetId;
        copy.assetProductMappingId = this.assetProductMappingId;
        copy.value = this.value;
        copy.costBasis = this.costBasis;
        copy.shortTermRealizedGain = this.shortTermRealizedGain;
        copy.shortTermUnrealizedGain = this.shortTermUnrealizedGain;
        copy.longTermRealizedGain = this.longTermRealizedGain;
        copy.longTermUnrealizedGain = this.longTermUnrealizedGain;
        return copy;
    }

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("Holding[");
        sb.append("id=").append(id);
        sb.append(separator).append("createdTimestamp=").append(createdTimestamp);
        sb.append(separator).append("updatedTimestamp=").append(updatedTimestamp);
        sb.append(separator).append("createdBy=").append(createdBy);
        sb.append(separator).append("updatedBy=").append(updatedBy);
        sb.append(separator).append("accountId=").append(accountId);
        sb.append(separator).append("productId=").append(productId);
        sb.append(separator).append("assetId=").append(assetId);
        sb.append(separator).append("assetProductMappingId=").append(assetProductMappingId);
        sb.append(separator).append("value=").append(value);
        sb.append(separator).append("costBasis=").append(costBasis);
        sb.append(separator).append("shortTermRealizedGain=").append(shortTermRealizedGain);
        sb.append(separator).append("shortTermUnrealizedGain=").append(shortTermUnrealizedGain);
        sb.append(separator).append("longTermRealizedGain=").append(longTermRealizedGain);
        sb.append(separator).append("longTermUnrealizedGain=").append(longTermUnrealizedGain);
        sb.append("]");
        return sb.toString();
    }
}
