## Postgres DB connection properties
spring:
 datasource:
  url: jdbc:postgresql://avs-qa-db.cyawwhid1s6w.us-east-1.rds.amazonaws.com/aum
  username: avsqa
  password: NqyXb7jqj9Ub7EiGF

server:
 port: 8080
 servlet:
  context-path: /aum

auth:
 security:
  allowed-issuers:
   # One entry per Cognito User Pool.
   # Format: https://cognito-idp.{region}.amazonaws.com/{userPoolId}
   # The value must match the `iss` claim in the JWT exactly.
   - "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LY7jo7QDt"
